### ISSUE TITLE
danke/merci

### ISSUE THREAD

**Issue by uahim** [tobika/artep7viewer#1]
I used to have a similiar overview (though with less data) generated with pure User JavaScript inside the browser, but it became impossible to do now that arte changed their "plus 7" page. 

that being said, thanks for adding the date - now your viewer is superior to the new official page.

**Comment by tobika** [comment]
thanks @uahim, it's always motivating to know someone finds it useful

since arte changed their website many information have gone missing, before I had the time and some nice global filters: cinema, news, history...
this is all I have at the moment http://www.arte.tv/guide/fr/plus7/videos?&sort=newest

but I really want to get the airtime back aswell, in the worst case I have to parse every video site

if you have any other ideas don't hesitate to share them :)
